// Categories

// T-Shirt
const T_Shirts = [
  {
    title: "Henly Shirt",
    sourceImg: "./img/product-8-1.jpg",
    sourceImg_2: "./img/product-8-2.jpg",
    price: 116,
    old_price: 200,
    off: 25,
    Availability: 8,
  },
  {
    title: "Glamora",
    sourceImg: "./img/product-1-1.jpg",
    sourceImg_2: "./img/product-1-2.jpg",
    price: 90,
    old_price: 150,
    off: 25,
    Availability: 3,
  },
  {
    title: "Urban Grove",
    sourceImg: "./img/product-2-1.jpg",
    sourceImg_2: "./img/product-2-2.jpg",
    price: 85,
    old_price: 135,
    off: 25,
    Availability: 5,
  },
  {
    title: "Urban Elan",
    sourceImg: "./img/product-2-1.jpg",
    sourceImg_2: "./img/product-2-2.jpg",
    price: 50,
    old_price: 100,
    off: 25,
    Availability: 9,
  },
  {
    title: "Urban moon",
    sourceImg: "./img/product-6-1.jpg",
    sourceImg_2: "./img/product-6-2.jpg",
    price: 200,
    old_price: 300,
    off: 25,
    Availability: 3,
  },
  {
    title: "Chic Aura",
    sourceImg: "./img/product-9-1.jpg",
    sourceImg_2: "./img/product-9-2.jpg",
    price: 50,
    old_price: 150,
    off: 25,
    Availability: 2,
  },
  {
    title: "Lux Avenue",
    sourceImg: "./img/product-12-1.jpg",
    sourceImg_2: "./img/product-12-2.jpg",
    price: 160,
    old_price: 550,
    off: 25,
    Availability: 8,
  },
];

// shoeses
const shoes = [
  {
    title: "black Shoes",
    sourceImg: "./img/product-3-1.jpg",
    sourceImg_2: "./img/product-3-2.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-1.jpg",
    sourceImg_2: "./img/Nike/s-2.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-2.jpg",
    sourceImg_2: "./img/Nike/s-3.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-3.jpg",
    sourceImg_2: "./img/Nike/s-4.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-4.jpg",
    sourceImg_2: "./img/Nike/s-5.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-5.jpg",
    sourceImg_2: "./img/Nike/s-6.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-6.jpg",
    sourceImg_2: "./img/Nike/s-7.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-7.jpg",
    sourceImg_2: "./img/Nike/s-8.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-8.jpg",
    sourceImg_2: "./img/Nike/s-9.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-9.jpg",
    sourceImg_2: "./img/Nike/s-8.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
];
// Sandal
const sandal = [
  {
    title: "Sandal Shoes",
    sourceImg: "./img/product-10-1.jpg",
    sourceImg_2: "./img/product-10-2.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-1.jpg",
    sourceImg_2: "./img/sandal/s-2.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-2.jpg",
    sourceImg_2: "./img/sandal/s-3.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-3.jpg",
    sourceImg_2: "./img/sandal/s-4.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-4.jpg",
    sourceImg_2: "./img/sandal/s-5.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-5.jpg",
    sourceImg_2: "./img/sandal/s-6.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-6.jpg",
    sourceImg_2: "./img/sandal/s-7.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-7.jpg",
    sourceImg_2: "./img/sandal/s-8.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-8.jpg",
    sourceImg_2: "./img/sandal/s-9.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-9.jpg",
    sourceImg_2: "./img/sandal/s-8.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
];
// Bags
const bags = [
  {
    title: "black bog",
    sourceImg: "./img/product-13-1.jpg",
    sourceImg_2: "./img/product-13-2.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "black bog",
    sourceImg: "./img/bags/b-1",
    sourceImg_2: "./img/bags/b-2",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "black bog",
    sourceImg: "./img/bags/b-2",
    sourceImg_2: "./img/bags/b-3",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "black bog",
    sourceImg: "./img/bags/b-3",
    sourceImg_2: "./img/bags/b-4",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "black bog",
    sourceImg: "./img/bags/b-4",
    sourceImg_2: "./img/bags/b-5",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "black bog",
    sourceImg: "./img/bags/b-5",
    sourceImg_2: "./img/bags/b-6",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "black bog",
    sourceImg: "./img/bags/b-6",
    sourceImg_2: "./img/bags/b-7",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "black bog",
    sourceImg: "./img/bags/b-7",
    sourceImg_2: "./img/bags/b-8",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "black bog",
    sourceImg: "./img/bags/b-8",
    sourceImg_2: "./img/bags/b-9",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "black bog",
    sourceImg: "./img/bags/b-9",
    sourceImg_2: "./img/bags/b-8",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
];
// scraf cop

const scraf_cop = [
  {
    title: "scraf cop heaven",
    sourceImg: "./img/product-5-1.jpg",
    sourceImg_2: "./img/product-5-2.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "scraf cop heaven",
    sourceImg: "./img/Scarfs/s-1.jpg",
    sourceImg_2: "./img/Scarfs/s-2.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "scraf cop heaven",
    sourceImg: "./img/Scarfs/s-2.jpg",
    sourceImg_2: "./img/Scarfs/s-3.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "scraf cop heaven",
    sourceImg: "./img/Scarfs/s-3.jpg",
    sourceImg_2: "./img/Scarfs/s-4.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "scraf cop heaven",
    sourceImg: "./img/Scarfs/s-4.jpg",
    sourceImg_2: "./img/Scarfs/s-5.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "scraf cop heaven",
    sourceImg: "./img/Scarfs/s-5.jpg",
    sourceImg_2: "./img/Scarfs/s-6.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "scraf cop heaven",
    sourceImg: "./img/Scarfs/s-6.jpg",
    sourceImg_2: "./img/Scarfs/s-7.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "scraf cop heaven",
    sourceImg: "./img/Scarfs/s-7.jpg",
    sourceImg_2: "./img/Scarfs/s-6.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
];
// jump sult
const jumpsult = [
  {
    title: "jump sult ",
    sourceImg: "./img/product-11-1.jpg",
    sourceImg_2: "./img/product-11-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "jump sult ",
    sourceImg: "./img/product-11-1.jpg",
    sourceImg_2: "./img/product-11-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "jump sult ",
    sourceImg: "./img/product-11-1.jpg",
    sourceImg_2: "./img/product-11-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "jump sult ",
    sourceImg: "./img/product-11-1.jpg",
    sourceImg_2: "./img/product-11-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "jump sult ",
    sourceImg: "./img/product-11-1.jpg",
    sourceImg_2: "./img/product-11-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "jump sult ",
    sourceImg: "./img/product-11-1.jpg",
    sourceImg_2: "./img/product-11-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "jump sult ",
    sourceImg: "./img/product-11-1.jpg",
    sourceImg_2: "./img/product-11-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "jump sult ",
    sourceImg: "./img/product-11-1.jpg",
    sourceImg_2: "./img/product-11-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "jump sult ",
    sourceImg: "./img/product-11-1.jpg",
    sourceImg_2: "./img/product-11-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
];

// pillow cases
const pillowcases = [

  {
    title: "pillow case Blue ",
    sourceImg: "./img/pillowcases/p-1.jpg",
    sourceImg_2: "./img/pillowcases/p-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "pillow case black ",
    sourceImg: "./img/pillowcases/p-2.jpg",
    sourceImg_2: "./img/pillowcases/p-3.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "pillow case lion ",
    sourceImg: "./img/pillowcases/p-3.jpg",
    sourceImg_2: "./img/pillowcases/p-4.png",
    price: 40,
    old_price: 240,
    off: 25,
    Availability: 12,
  },
  {
    title: "pillow case fight ",
    sourceImg: "./img/pillowcases/p-4.png",
    sourceImg_2: "./img/pillowcases/p-5.jpg",
    price: 140,
    old_price: 600,
    off: 25,
    Availability: 13,
  },
  {
    title: "pillow case yellow ",
    sourceImg: "./img/pillowcases/p-5.jpg",
    sourceImg_2: "./img/pillowcases/p-6.jpg",
    price: 120,
    old_price: 600,
    off: 25,
    Availability: 42,
  },
  {
    title: "pillow case white ",
    sourceImg: "./img/pillowcases/p-6.jpg",
    sourceImg_2: "./img/pillowcases/p-7.jpg",
    price: 20,
    old_price: 100,
    off: 25,
    Availability: 29,
  },
  {
    title: "pillow case orange ",
    sourceImg: "./img/pillowcases/p-7.jpg",
    sourceImg_2: "./img/pillowcases/p-8.jpg",
    price: 100,
    old_price: 400,
    off: 25,
    Availability: 228,
  },
  {
    title: "pillow case fanta ",
    sourceImg: "./img/pillowcases/p-8.jpg",
    sourceImg_2: "./img/pillowcases/p-9.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 212,
  },
  {
    title: "pillow case brown ",
    sourceImg: "./img/pillowcases/p-9.jpg",
    sourceImg_2: "./img/pillowcases/p-8.jpg",
    price: 15,
    old_price: 60,
    off: 25,
    Availability: 223,
  },
];

// Hats

const hats = [
  {
    title: "Hats case Blue ",
    sourceImg: "../img/Hats/h-1.jpg",
    sourceImg_2: "../img/Hats/h-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "Hats case black ",
    sourceImg: "../img/Hats/h-2.jpg",
    sourceImg_2: "../img/Hats/h-3.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "Hats case lion ",
    sourceImg: "../img/Hats/h-3.jpg",
    sourceImg_2: "../img/Hats/h-4.jpg",
    price: 40,
    old_price: 240,
    off: 25,
    Availability: 12,
  },
  {
    title: "hats case fight ",
    sourceImg: "../img/Hats/h-4.jpg",
    sourceImg_2: "../img/Hats/h-5.jpg",
    price: 140,
    old_price: 600,
    off: 25,
    Availability: 13,
  },
  {
    title: "Hats case yellow ",
    sourceImg: "../img/Hats/h-5.jpg",
    sourceImg_2: "../img/Hats/h-6.jpg",
    price: 120,
    old_price: 600,
    off: 25,
    Availability: 42,
  },
  {
    title: "Hats case white ",
    sourceImg: "../img/Hats/h-6.jpg",
    sourceImg_2: "../img/Hats/h-7.jpg",
    price: 20,
    old_price: 100,
    off: 25,
    Availability: 29,
  },
  {
    title: "hats case orange ",
    sourceImg: "../img/Hats/h-7.jpg",
    sourceImg_2: "../img/Hats/h-8.jpg",
    price: 100,
    old_price: 400,
    off: 25,
    Availability: 228,
  },
  {
    title: "Hats case fanta ",
    sourceImg: "../img/Hats/h-8.jpg",
    sourceImg_2: "../img/Hats/h-9.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 212,
  },
  {
    title: "Hats case brown ",
    sourceImg: "../img/Hats/h-9.jpg",
    sourceImg_2: "../img/Hats/h-8.jpg",
    price: 15,
    old_price: 60,
    off: 25,
    Availability: 223,
  },
]
// All Items

const allItems = [
  {
    title: "Henly Shirt",
    sourceImg: "./img/product-8-1.jpg",
    sourceImg_2: "./img/product-8-2.jpg",
    price: 116,
    old_price: 200,
    off: 25,
    Availability: 8,
  },
  {
    title: "Glamora",
    sourceImg: "./img/product-1-1.jpg",
    sourceImg_2: "./img/product-1-2.jpg",
    price: 90,
    old_price: 150,
    off: 25,
    Availability: 3,
  },
  {
    title: "Urban Grove",
    sourceImg: "./img/product-2-1.jpg",
    sourceImg_2: "./img/product-2-2.jpg",
    price: 85,
    old_price: 135,
    off: 25,
    Availability: 5,
  },
  {
    title: "Urban Elan",
    sourceImg: "./img/product-2-1.jpg",
    sourceImg_2: "./img/product-2-2.jpg",
    price: 50,
    old_price: 100,
    off: 25,
    Availability: 9,
  },
  {
    title: "Urban moon",
    sourceImg: "./img/product-6-1.jpg",
    sourceImg_2: "./img/product-6-2.jpg",
    price: 200,
    old_price: 300,
    off: 25,
    Availability: 3,
  },
  {
    title: "Chic Aura",
    sourceImg: "./img/product-9-1.jpg",
    sourceImg_2: "./img/product-9-2.jpg",
    price: 50,
    old_price: 150,
    off: 25,
    Availability: 2,
  },
  {
    title: "Lux Avenue",
    sourceImg: "./img/product-12-1.jpg",
    sourceImg_2: "./img/product-12-2.jpg",
    price: 160,
    old_price: 550,
    off: 25,
    Availability: 8,
  },
  {
    title: "jump sult ",
    sourceImg: "./img/product-11-1.jpg",
    sourceImg_2: "./img/product-11-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "Hats case Blue ",
    sourceImg: "../img/Hats/h-1.jpg",
    sourceImg_2: "../img/Hats/h-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "Hats case black ",
    sourceImg: "../img/Hats/h-2.jpg",
    sourceImg_2: "../img/Hats/h-3.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "Hats case lion ",
    sourceImg: "../img/Hats/h-3.jpg",
    sourceImg_2: "../img/Hats/h-4.jpg",
    price: 40,
    old_price: 240,
    off: 25,
    Availability: 12,
  },
  {
    title: "hats case fight ",
    sourceImg: "../img/Hats/h-4.jpg",
    sourceImg_2: "../img/Hats/h-5.jpg",
    price: 140,
    old_price: 600,
    off: 25,
    Availability: 13,
  },
  {
    title: "Hats case yellow ",
    sourceImg: "../img/Hats/h-5.jpg",
    sourceImg_2: "../img/Hats/h-6.jpg",
    price: 120,
    old_price: 600,
    off: 25,
    Availability: 42,
  },
  {
    title: "Hats case white ",
    sourceImg: "../img/Hats/h-6.jpg",
    sourceImg_2: "../img/Hats/h-7.jpg",
    price: 20,
    old_price: 100,
    off: 25,
    Availability: 29,
  },
  {
    title: "hats case orange ",
    sourceImg: "../img/Hats/h-7.jpg",
    sourceImg_2: "../img/Hats/h-8.jpg",
    price: 100,
    old_price: 400,
    off: 25,
    Availability: 228,
  },
  {
    title: "Hats case fanta ",
    sourceImg: "../img/Hats/h-8.jpg",
    sourceImg_2: "../img/Hats/h-9.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 212,
  },
  {
    title: "scraf cop heaven",
    sourceImg: "./img/product-5-1.jpg",
    sourceImg_2: "./img/product-5-2.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "scraf cop heaven",
    sourceImg: "./img/Scarfs/s-1.jpg",
    sourceImg_2: "./img/Scarfs/s-2.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "scraf cop heaven",
    sourceImg: "./img/Scarfs/s-2.jpg",
    sourceImg_2: "./img/Scarfs/s-3.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "scraf cop heaven",
    sourceImg: "./img/Scarfs/s-3.jpg",
    sourceImg_2: "./img/Scarfs/s-4.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "scraf cop heaven",
    sourceImg: "./img/Scarfs/s-4.jpg",
    sourceImg_2: "./img/Scarfs/s-5.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/product-10-1.jpg",
    sourceImg_2: "./img/product-10-2.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-1.jpg",
    sourceImg_2: "./img/sandal/s-2.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-2.jpg",
    sourceImg_2: "./img/sandal/s-3.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-3.jpg",
    sourceImg_2: "./img/sandal/s-4.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-4.jpg",
    sourceImg_2: "./img/sandal/s-5.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-5.jpg",
    sourceImg_2: "./img/sandal/s-6.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-6.jpg",
    sourceImg_2: "./img/sandal/s-7.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-7.jpg",
    sourceImg_2: "./img/sandal/s-8.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-8.jpg",
    sourceImg_2: "./img/sandal/s-9.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-9.jpg",
    sourceImg_2: "./img/sandal/s-8.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "scraf cop heaven",
    sourceImg: "./img/Scarfs/s-5.jpg",
    sourceImg_2: "./img/Scarfs/s-6.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "scraf cop heaven",
    sourceImg: "./img/Scarfs/s-6.jpg",
    sourceImg_2: "./img/Scarfs/s-7.jpg",
    price: 50,
    old_price: 200,
    off: 25,
    Availability: 9,
  },
  {
    title: "scraf cop heaven",
    sourceImg: "./img/Scarfs/s-7.jpg",
    sourceImg_2: "./img/Scarfs/s-6.jpg",
    price: 75,
    old_price: 300,
    off: 25,
    Availability: 9,
  },
  {
    title: "Hats case brown ",
    sourceImg: "../img/Hats/h-9.jpg",
    sourceImg_2: "../img/Hats/h-8.jpg",
    price: 80,
    old_price: 320,
    off: 25,
    Availability: 223,
  },
  {
    title: "pillow case Blue ",
    sourceImg: "./img/pillowcases/p-1.jpg",
    sourceImg_2: "./img/pillowcases/p-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "pillow case black ",
    sourceImg: "./img/pillowcases/p-2.jpg",
    sourceImg_2: "./img/pillowcases/p-3.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "pillow case lion ",
    sourceImg: "./img/pillowcases/p-3.jpg",
    sourceImg_2: "./img/pillowcases/p-4.png",
    price: 40,
    old_price: 240,
    off: 25,
    Availability: 12,
  },
  {
    title: "pillow case fight ",
    sourceImg: "./img/pillowcases/p-4.png",
    sourceImg_2: "./img/pillowcases/p-5.jpg",
    price: 140,
    old_price: 600,
    off: 25,
    Availability: 13,
  },
  {
    title: "pillow case yellow ",
    sourceImg: "./img/pillowcases/p-5.jpg",
    sourceImg_2: "./img/pillowcases/p-6.jpg",
    price: 120,
    old_price: 600,
    off: 25,
    Availability: 42,
  },
  {
    title: "pillow case white ",
    sourceImg: "./img/pillowcases/p-6.jpg",
    sourceImg_2: "./img/pillowcases/p-7.jpg",
    price: 20,
    old_price: 100,
    off: 25,
    Availability: 29,
  },
  {
    title: "black bag",
    sourceImg: "./img/product-13-1.jpg",
    sourceImg_2: "./img/product-13-2.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "black bag",
    sourceImg: "./img/bags/b-1",
    sourceImg_2: "./img/bags/b-2",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "black bag",
    sourceImg: "./img/bags/b-2",
    sourceImg_2: "./img/bags/b-3",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "black bag",
    sourceImg: "./img/bags/b-3",
    sourceImg_2: "./img/bags/b-4",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "black bag",
    sourceImg: "./img/bags/b-4",
    sourceImg_2: "./img/bags/b-5",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "black bag",
    sourceImg: "./img/bags/b-5",
    sourceImg_2: "./img/bags/b-6",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "Yellow bag",
    sourceImg: "./img/bags/b-6",
    sourceImg_2: "./img/bags/b-7",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "black bog",
    sourceImg: "./img/bags/b-7",
    sourceImg_2: "./img/bags/b-8",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "black bog",
    sourceImg: "./img/bags/b-8",
    sourceImg_2: "./img/bags/b-9",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "black bog",
    sourceImg: "./img/bags/b-9",
    sourceImg_2: "./img/bags/b-8",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "pillow case orange ",
    sourceImg: "./img/pillowcases/p-7.jpg",
    sourceImg_2: "./img/pillowcases/p-8.jpg",
    price: 100,
    old_price: 400,
    off: 25,
    Availability: 228,
  },
  {
    title: "pillow case fanta ",
    sourceImg: "./img/pillowcases/p-8.jpg",
    sourceImg_2: "./img/pillowcases/p-9.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 212,
  },
  {
    title: "pillow case brown ",
    sourceImg: "./img/pillowcases/p-9.jpg",
    sourceImg_2: "./img/pillowcases/p-8.jpg",
    price: 15,
    old_price: 60,
    off: 25,
    Availability: 223,
  },
]










// Featured

const featured = [
  {
    title: "Henly Shirt",
    sourceImg: "./img/product-8-1.jpg",
    sourceImg_2: "./img/product-8-2.jpg",
    price: 116,
    old_price: 200,
    off: 25,
    Availability: 8,
  },
  {
    title: "Glamora",
    sourceImg: "./img/product-1-1.jpg",
    sourceImg_2: "./img/product-1-2.jpg",
    price: 90,
    old_price: 150,
    off: 25,
    Availability: 3,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/product-10-1.jpg",
    sourceImg_2: "./img/product-10-2.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "jump sult ",
    sourceImg: "./img/product-11-1.jpg",
    sourceImg_2: "./img/product-11-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "Glamora",
    sourceImg: "./img/product-1-2.jpg",
    sourceImg_2: "./img/product-1-1.jpg",
    price: 90,
    old_price: 150,
    off: 25,
    Availability: 3,
  },
  {
    title: "black Shoes",
    sourceImg: "./img/product-3-1.jpg",
    sourceImg_2: "./img/product-3-2.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Urban Grove",
    sourceImg: "./img/product-2-2.jpg",
    sourceImg_2: "./img/product-2-1.jpg",
    price: 85,
    old_price: 135,
    off: 25,
    Availability: 5,
  },
  {
    title: "black bog",
    sourceImg: "./img/product-13-1.jpg",
    sourceImg_2: "./img/product-13-2.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "Chic Aura",
    sourceImg: "./img/product-9-1.jpg",
    sourceImg_2: "./img/product-9-2.jpg",
    price: 50,
    old_price: 150,
    off: 25,
    Availability: 2,
  },
  {
    title: "Hats case lion ",
    sourceImg: "../img/Hats/h-3.jpg",
    sourceImg_2: "../img/Hats/h-4.jpg",
    price: 40,
    old_price: 240,
    off: 25,
    Availability: 12,
  },
  {
    title: "Lux Avenue",
    sourceImg: "./img/product-12-2.jpg",
    sourceImg_2: "./img/product-12-1.jpg",
    price: 160,
    old_price: 550,
    off: 25,
    Availability: 8,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-4.jpg",
    sourceImg_2: "./img/sandal/s-5.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
]

const popular = [
  {
    title: "Chic Aura",
    sourceImg: "./img/product-9-1.jpg",
    sourceImg_2: "./img/product-9-2.jpg",
    price: 50,
    old_price: 150,
    off: 25,
    Availability: 2,
  },
  {
    title: "Glamora",
    sourceImg: "./img/product-1-1.jpg",
    sourceImg_2: "./img/product-1-2.jpg",
    price: 90,
    old_price: 150,
    off: 25,
    Availability: 3,
  },
  {
    title: "Normal Sandal",
    sourceImg: "./img/product-10-1.jpg",
    sourceImg_2: "./img/product-10-2.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "jump sult ",
    sourceImg: "./img/product-11-1.jpg",
    sourceImg_2: "./img/product-11-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },

  {
    title: "Nike Shoes Pro",
    sourceImg: "./img/Nike/s-3.jpg",
    sourceImg_2: "./img/Nike/s-4.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Urban Grove",
    sourceImg: "./img/product-2-2.jpg",
    sourceImg_2: "./img/product-2-1.jpg",
    price: 85,
    old_price: 135,
    off: 25,
    Availability: 5,
  },
  {
    title: "whity bog",
    sourceImg: "./img/bags/b-6",
    sourceImg_2: "./img/bags/b-7",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "Chic Aura",
    sourceImg: "./img/product-9-1.jpg",
    sourceImg_2: "./img/product-9-2.jpg",
    price: 50,
    old_price: 150,
    off: 25,
    Availability: 2,
  },
  {
    title: "Hats case Blue ",
    sourceImg: "../img/Hats/h-1.jpg",
    sourceImg_2: "../img/Hats/h-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },
  {
    title: "Sandal Shoes",
    sourceImg: "./img/sandal/s-9.jpg",
    sourceImg_2: "./img/sandal/s-8.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
]

// new added
const Newadded = [
  {
    title: "scraf cop heaven",
    sourceImg: "./img/Scarfs/s-2.jpg",
    sourceImg_2: "./img/Scarfs/s-3.jpg",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "Henly Shirt",
    sourceImg: "./img/product-8-1.jpg",
    sourceImg_2: "./img/product-8-2.jpg",
    price: 116,
    old_price: 200,
    off: 25,
    Availability: 8,
  },
  {
    title: "Urban Grove",
    sourceImg: "./img/product-2-1.jpg",
    sourceImg_2: "./img/product-2-2.jpg",
    price: 85,
    old_price: 135,
    off: 25,
    Availability: 5,
  },
  {
    title: "Normal Sandal",
    sourceImg: "./img/product-10-1.jpg",
    sourceImg_2: "./img/product-10-2.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "jump sult ",
    sourceImg: "./img/product-11-1.jpg",
    sourceImg_2: "./img/product-11-2.jpg",
    price: 130,
    old_price: 600,
    off: 25,
    Availability: 22,
  },

  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-5.jpg",
    sourceImg_2: "./img/Nike/s-6.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Urban moon",
    sourceImg: "./img/product-6-1.jpg",
    sourceImg_2: "./img/product-6-2.jpg",
    price: 200,
    old_price: 300,
    off: 25,
    Availability: 3,
  },
  {
    title: "black bag",
    sourceImg: "./img/bags/b-8",
    sourceImg_2: "./img/bags/b-9",
    price: 60,
    old_price: 160,
    off: 25,
    Availability: 9,
  },
  {
    title: "Chic Aura",
    sourceImg: "./img/product-9-1.jpg",
    sourceImg_2: "./img/product-9-2.jpg",
    price: 50,
    old_price: 150,
    off: 25,
    Availability: 2,
  },
  {
    title: "Hats case yellow ",
    sourceImg: "../img/Hats/h-5.jpg",
    sourceImg_2: "../img/Hats/h-6.jpg",
    price: 120,
    old_price: 600,
    off: 25,
    Availability: 42,
  },
  {
    title: "Sandal Pro ",
    sourceImg: "./img/sandal/s-5.jpg",
    sourceImg_2: "./img/sandal/s-6.jpg",
    price: 30,
    old_price: 120,
    off: 25,
    Availability: 25,
  },
  {
    title: "black Shoes",
    sourceImg: "./img/product-3-1.jpg",
    sourceImg_2: "./img/product-3-2.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-1.jpg",
    sourceImg_2: "./img/Nike/s-2.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-2.jpg",
    sourceImg_2: "./img/Nike/s-3.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-3.jpg",
    sourceImg_2: "./img/Nike/s-4.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-4.jpg",
    sourceImg_2: "./img/Nike/s-5.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-5.jpg",
    sourceImg_2: "./img/Nike/s-6.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-6.jpg",
    sourceImg_2: "./img/Nike/s-7.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-7.jpg",
    sourceImg_2: "./img/Nike/s-8.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-8.jpg",
    sourceImg_2: "./img/Nike/s-9.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
  {
    title: "Nike shoes",
    sourceImg: "./img/Nike/s-9.jpg",
    sourceImg_2: "./img/Nike/s-8.jpg",
    price: 55,
    old_price: 160,
    off: 25,
    Availability: 2,
  },
]